from __future__ import annotations

MODULE_SOURCES = {
    "company": [
        {
            "name": "ITmedia Executive RSS",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/executive.xml",
            "lang": "ja",
            "region": "domestic",
            "weight": 5,
        },
        {
            "name": "ITmedia Business Online RSS",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/business.xml",
            "lang": "ja",
            "region": "domestic",
            "weight": 5,
        },
        {
            "name": "ITmedia News Industry RSS",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/news_industry.xml",
            "lang": "ja",
            "region": "domestic",
            "weight": 4,
        },
        {
            "name": "ITmedia News Bursts RSS",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/news_bursts.xml",
            "lang": "ja",
            "region": "domestic",
            "weight": 3,
        },
        {
            "name": "METI Press Releases",
            "type": "html",
            "url": "https://www.meti.go.jp/press/",
            "item_selector": "a[href*='/press/']",
            "include_url_patterns": ["/press/"],
            "exclude_url_patterns": [".pdf", ".xlsx", "mailto:"],
            "base_url": "https://www.meti.go.jp",
            "lang": "ja",
            "region": "domestic",
            "weight": 4,
        },

        {
            "name": "TechTarget Japan Business RSS",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/tt_business.xml",
            "lang": "ja",
            "region": "domestic",
            "weight": 4,
        },
        {
            "name": "ITmedia AI+",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/aiplus.xml",
            "fallback_urls": ["https://rss.itmedia.co.jp/rss/2.0/news_bursts.xml"],
            "lang": "ja",
            "region": "domestic",
            "weight": 4,
        },
        {
            "name": "Google AI Blog",
            "type": "rss",
            "url": "https://blog.google/technology/ai/rss/",
            "lang": "en",
            "region": "global",
            "weight": 5,
        },
        {
            "name": "Microsoft Blogs",
            "type": "rss",
            "url": "https://blogs.microsoft.com/feed/",
            "lang": "en",
            "region": "global",
            "weight": 4,
        },
        {
            "name": "NVIDIA Blog",
            "type": "rss",
            "url": "https://blogs.nvidia.com/feed/",
            "lang": "en",
            "region": "global",
            "weight": 4,
        },
        {
            "name": "Intel Press Releases",
            "type": "html",
            "url": "https://www.intc.com/news-events/press-releases",
            "item_selector": "a[href*='/news-events/press-releases/detail/']",
            "include_url_patterns": ["/news-events/press-releases/detail/"],
            "exclude_url_patterns": ["mailto:", "javascript:"],
            "base_url": "https://www.intc.com",
            "lang": "en",
            "region": "global",
            "weight": 4,
        },
    ],
    "price": [
        {
            "name": "Federal Reserve Press Releases",
            "type": "html",
            "url": "https://www.federalreserve.gov/newsevents/pressreleases.htm",
            "fallback_urls": ["https://www.federalreserve.gov/newsevents.htm"],
            "item_selector": "a[href*='/newsevents/pressreleases/']",
            "include_url_patterns": ["/newsevents/pressreleases/"],
            "exclude_url_patterns": [".pdf", "calendar", "feeds"],
            "base_url": "https://www.federalreserve.gov",
            "lang": "en",
            "region": "global",
            "weight": 5,
        },
        {
            "name": "Bank of Japan News",
            "type": "html",
            "url": "https://www.boj.or.jp/whatsnew/index.htm",
            "fallback_urls": ["https://www.boj.or.jp/en/whatsnew/index.htm", "https://www.boj.or.jp/"],
            "item_selector": "a[href*='/announcements/'], a[href*='/research/'], a[href*='/statistics/'], a[href*='/en/announcements/'], a[href*='/en/research/'], a[href*='/en/statistics/']",
            "include_url_patterns": ["/announcements/", "/research/", "/statistics/"],
            "exclude_url_patterns": [".pdf", ".xlsx", "rss", "tips"],
            "base_url": "https://www.boj.or.jp",
            "lang": "ja",
            "region": "domestic",
            "weight": 5,
        },
        {
            "name": "ITmedia News Domestic RSS",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/news_domestic.xml",
            "lang": "ja",
            "region": "domestic",
            "weight": 3,
        },
    ],
    "supply_chain": [
        {
            "name": "MONOist RSS",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/monoist.xml",
            "lang": "ja",
            "region": "domestic",
            "weight": 5,
        },
        {
            "name": "MONOist Manufacturing Management RSS",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/mn_pro.xml",
            "lang": "ja",
            "region": "domestic",
            "weight": 5,
        },
        {
            "name": "EE Times Japan RSS",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/eetimes.xml",
            "lang": "ja",
            "region": "domestic",
            "weight": 4,
        },
        {
            "name": "SEMI Press Releases",
            "type": "html",
            "url": "https://www.semi.org/en/news-media-press/semi-press-releases/press-archive",
            "item_selector": "a[href*='/en/semi-press-release/']",
            "include_url_patterns": ["/en/semi-press-release/"],
            "exclude_url_patterns": ["mailto:", "javascript:", ".pdf"],
            "base_url": "https://www.semi.org",
            "lang": "en",
            "region": "global",
            "weight": 5,
        },
    ],
    "failure": [
        {
            "name": "ITmedia Enterprise Security",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/enterprise_security.xml",
            "fallback_urls": ["https://rss.itmedia.co.jp/rss/2.0/news_bursts.xml"],
            "lang": "ja",
            "region": "domestic",
            "weight": 4,
        },
        {
            "name": "The Hacker News",
            "type": "rss",
            "url": "https://feeds.feedburner.com/TheHackersNews",
            "lang": "en",
            "region": "global",
            "weight": 5,
        },
        {
            "name": "BleepingComputer",
            "type": "rss",
            "url": "https://www.bleepingcomputer.com/feed/",
            "lang": "en",
            "region": "global",
            "weight": 5,
        },
        {
            "name": "Krebs on Security",
            "type": "rss",
            "url": "https://krebsonsecurity.com/feed/",
            "lang": "en",
            "region": "global",
            "weight": 5,
        },
        {
            "name": "CISA News",
            "type": "html",
            "url": "https://www.cisa.gov/news-events/news",
            "item_selector": "a[href*='/news-events/news/']",
            "include_url_patterns": ["/news-events/news/"],
            "exclude_url_patterns": ["search", "subscribe"],
            "base_url": "https://www.cisa.gov",
            "lang": "en",
            "region": "global",
            "weight": 5,
        },
        {
            "name": "IPA Security Alerts",
            "type": "html",
            "url": "https://www.ipa.go.jp/security/security-alert/index.html",
            "fallback_urls": ["https://www.ipa.go.jp/security/", "https://www.ipa.go.jp/security/vuln/icat.html"],
            "item_selector": "a[href*='/security/security-alert/'], a[href*='/security/alert/'], a[href*='/security/vuln/']",
            "include_url_patterns": ["/security/"],
            "exclude_url_patterns": [".pdf", ".zip", "mailto:", "javascript:", "/rss"],
            "base_url": "https://www.ipa.go.jp",
            "lang": "ja",
            "region": "domestic",
            "weight": 5,
        },
    ],
    "earnings": [
        {
            "name": "ITmedia Business Online RSS",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/business.xml",
            "lang": "ja",
            "region": "domestic",
            "weight": 4,
        },
        {
            "name": "ITmedia News Industry RSS",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/news_industry.xml",
            "lang": "ja",
            "region": "domestic",
            "weight": 4,
        },
        {
            "name": "Intel Financial Releases",
            "type": "html",
            "url": "https://www.intc.com/news-events/press-releases?category=financial",
            "item_selector": "a[href*='/news-events/press-releases/detail/']",
            "include_url_patterns": ["/news-events/press-releases/detail/"],
            "exclude_url_patterns": ["mailto:", "javascript:"],
            "base_url": "https://www.intc.com",
            "lang": "en",
            "region": "global",
            "weight": 5,
        },
        {
            "name": "Samsung Global Newsroom",
            "type": "rss",
            "url": "https://news.samsung.com/global/feed",
            "lang": "en",
            "region": "global",
            "weight": 4,
        },
        {
            "name": "Yahoo Finance Earnings",
            "type": "rss",
            "url": "https://feeds.finance.yahoo.com/rss/2.0/headline?s=earnings&region=US&lang=en-US",
            "lang": "en",
            "region": "global",
            "weight": 5,
        },
        {
            "name": "CNBC Earnings",
            "type": "rss",
            "url": "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=15839069",
            "lang": "en",
            "region": "global",
            "weight": 5,
        },
        {
            "name": "MarketWatch Top Stories",
            "type": "rss",
            "url": "https://feeds.content.dowjones.io/public/rss/mw_realtimeheadlines",
            "fallback_urls": ["https://www.marketwatch.com/rss/topstories"],
            "lang": "en",
            "region": "global",
            "weight": 4,
        },
        {
            "name": "東洋経済オンライン 企業・経営",
            "type": "rss",
            "url": "https://toyokeizai.net/list/feed/rss",
            "lang": "ja",
            "region": "domestic",
            "weight": 4,
        },
    ],
    "geo_risk": [
        {
            "name": "NIST AI Risk Management",
            "type": "html",
            "url": "https://www.nist.gov/itl/ai-risk-management-framework",
            "fallback_urls": ["https://www.nist.gov/news-events/news"],
            "item_selector": "a[href*='/news-events/'], a[href*='/programs-projects/'], a[href*='/events/']",
            "include_url_patterns": ["/news-events/", "/programs-projects/", "/events/"],
            "exclude_url_patterns": ["mailto:", "#"],
            "base_url": "https://www.nist.gov",
            "lang": "en",
            "region": "global",
            "weight": 5,
        },
        {
            "name": "European Commission Digital Strategy",
            "type": "html",
            "url": "https://digital-strategy.ec.europa.eu/en/policies/european-approach-artificial-intelligence",
            "item_selector": "a[href*='/en/'], article a[href*='/en/']",
            "include_url_patterns": ["/en/"],
            "exclude_url_patterns": ["mailto:", "download", ".pdf"],
            "base_url": "https://digital-strategy.ec.europa.eu",
            "lang": "en",
            "region": "global",
            "weight": 5,
        },
        {
            "name": "METI English Press",
            "type": "html",
            "url": "https://www.meti.go.jp/english/press/index.html",
            "item_selector": "a[href*='/english/press/']",
            "include_url_patterns": ["/english/press/"],
            "exclude_url_patterns": [".pdf", ".xlsx", "mailto:"],
            "base_url": "https://www.meti.go.jp",
            "lang": "ja",
            "region": "domestic",
            "weight": 5,
        },
        {
            "name": "Digital Agency News",
            "type": "html",
            "url": "https://www.digital.go.jp/news",
            "item_selector": "a[href*='/news/']",
            "include_url_patterns": ["/news/"],
            "exclude_url_patterns": [".pdf", "mailto:"],
            "base_url": "https://www.digital.go.jp",
            "lang": "ja",
            "region": "domestic",
            "weight": 4,
        },
        {
            "name": "MOFA Press Releases",
            "type": "html",
            "url": "https://www.mofa.go.jp/press/release/index.html",
            "fallback_urls": ["https://www.mofa.go.jp/press/release/202604_index.html", "https://www.mofa.go.jp/press/release/202603_index.html"],
            "item_selector": "a[href*='/press/release/'], a[href*='/whats/']",
            "include_url_patterns": ["/press/release/", "/whats/"],
            "exclude_url_patterns": [".pdf", "mailto:"],
            "base_url": "https://www.mofa.go.jp",
            "lang": "ja",
            "region": "domestic",
            "weight": 4,
        },

    ],
    "talent": [
        {
            "name": "MONOist Career RSS",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/mn_career.xml",
            "lang": "ja",
            "region": "domestic",
            "weight": 4,
        },
        {
            "name": "TechTarget Japan Business RSS",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/tt_business.xml",
            "lang": "ja",
            "region": "domestic",
            "weight": 4,
        },
        {
            "name": "ITmedia Executive RSS",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/executive.xml",
            "lang": "ja",
            "region": "domestic",
            "weight": 4,
        },
        {
            "name": "ITmedia News Bursts RSS",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/news_bursts.xml",
            "lang": "ja",
            "region": "domestic",
            "weight": 3,
        },

        {
            "name": "TechCrunch",
            "type": "rss",
            "url": "https://techcrunch.com/feed/",
            "lang": "en",
            "region": "global",
            "weight": 3,
        },
        {
            "name": "Wired Business",
            "type": "rss",
            "url": "https://www.wired.com/feed/category/business/latest/rss",
            "lang": "en",
            "region": "global",
            "weight": 3,
        },
    ],
    "product": [
        {
            "name": "ITmedia AI+",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/aiplus.xml",
            "lang": "ja",
            "region": "domestic",
            "weight": 4,
        },
        {
            "name": "ITmedia NEWS Domestic",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/news_domestic.xml",
            "lang": "ja",
            "region": "domestic",
            "weight": 4,
        },
        {
            "name": "MONOist RSS",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/monoist.xml",
            "lang": "ja",
            "region": "domestic",
            "weight": 4,
        },
        {
            "name": "ITmedia News Bursts RSS",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/news_bursts.xml",
            "lang": "ja",
            "region": "domestic",
            "weight": 3,
        },
        {
            "name": "ITmedia PC USER RSS",
            "type": "rss",
            "url": "https://rss.itmedia.co.jp/rss/2.0/pcuser.xml",
            "lang": "ja",
            "region": "domestic",
            "weight": 3,
        },

        {
            "name": "Intel News & Events",
            "type": "html",
            "url": "https://www.intc.com/news-events",
            "item_selector": "a[href*='/news-events/press-releases/detail/']",
            "include_url_patterns": ["/news-events/press-releases/detail/"],
            "exclude_url_patterns": ["mailto:", "javascript:"],
            "base_url": "https://www.intc.com",
            "lang": "en",
            "region": "global",
            "weight": 4,
        },
        {
            "name": "Google AI Blog",
            "type": "rss",
            "url": "https://blog.google/technology/ai/rss/",
            "lang": "en",
            "region": "global",
            "weight": 5,
        },
        {
            "name": "Microsoft Blogs",
            "type": "rss",
            "url": "https://blogs.microsoft.com/feed/",
            "lang": "en",
            "region": "global",
            "weight": 4,
        },
    ],
}

MODULE_LABELS = {
    "company": "Company",
    "price": "Price",
    "supply_chain": "Supply Chain",
    "failure": "Failure",
    "earnings": "Earnings",
    "geo_risk": "Geo Risk",
    "talent": "Talent",
    "product": "Product",
}
