name: HTMLを更新する

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 6 * * *'
    - cron: '0 12 * * *'
    - cron: '0 18 * * *'

permissions:
  contents: write

jobs:

  group1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements_all.txt

      - run: python ai_plus/app/main.py
      - run: python it_plus/app/main.py
      - run: python market_plus/app/main.py
      - run: python memory_market_plus/app/main.py
      - run: python pc_industry_suite/app/main.py

      - uses: actions/upload-artifact@v4
        with:
          name: group1
          path: "**/output/*.html"

  group2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements_all.txt

      - run: python auto_industry_suite/app/main.py
      - run: python camera_industry_suite/app/main.py
      - run: python dog_information_suite/app/main.py
      - run: python smart_news_viewer/app/main.py
      - run: python Strategic_IT_Suite/app/main.py

      - uses: actions/upload-artifact@v4
        with:
          name: group2
          path: "**/output/*.html"

  group3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements_all.txt

      - run: python travel_search_plus/app/main.py
      - run: python Spot_Selection_Navigator/app/main.py
      - run: python IdeaTrendEngine/app/main.py
      - run: python takarazuka_information_suite/app/main.py
      - run: python takarazuka_info_B/app/main.py

      - uses: actions/upload-artifact@v4
        with:
          name: group3
          path: "**/output/*.html"

  commit:
    needs: [group1, group2, group3]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4

      - name: ファイル統合
        run: |
          cp -r group1/* . || true
          cp -r group2/* . || true
          cp -r group3/* . || true

      - name: commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "parallel update" || echo no changes
          git push
